refactor: Break out `usd-oracle` directory in maple-core to be a submodule dapptools project (SC-3068)
maple-labs/usd-oracle pull request #1
Opened 2021-07-29 07:50 UTC by satyamakgec

2021-07-29 10:00 UTC, deluca-mike requested changes, later dismissed
The circle ci `config.yml` should still be the `dapp_test` with the 2 runs steps.

2021-07-29 10:00 UTC, deluca-mike commented on contracts/test/UsdOracle.t.sol
> +pragma experimental ABIEncoderV2;
Not critical, but this can be removed now.

2021-07-29 10:00 UTC, deluca-mike commented on config/ci.json
> +    },
This is not necessary as it's not a unique entry point with respect to ci.

2021-07-29 10:00 UTC, deluca-mike commented on config/dev.json
> +    },
This is not necessary as it's not a unique entry point with respect to dev.

2021-07-29 10:00 UTC, deluca-mike commented on config/prod.json
> +    },
This is not necessary as it's not a unique entry point with respect to prod.

2021-08-02 01:34 UTC, lucas-manuel approved these changes

2021-08-02 01:36 UTC, merged